### ISSUE TITLE
Provide function to extract Json.Decode.Decoder?

### ISSUE THREAD

**Issue by rupertlssmith** [MartinSStewart/elm-serialize#17]
Would it be possible to have a function like this:

```
asDecoder : Codec e a -> Decoder a
```

to extract a `Decoder`? This could be useful when combining `Codec`s with other code that is handling JSON but is not using `Codec`s. For example, I would like to use the `elm-geometry-serialize` package to add some fields to some existing decoders.

**Comment by MartinSStewart** [comment]
I've had thoughts about adding that but I think there was some difficultly that made me put it off. I unfortunately don't remember what it was but I can give this a shot and see if I run into the problem again.

**Comment by MartinSStewart** [comment]
What do you think of these type signatures?
```elm
-- Converts any error information into a String so that the Json.Decoder can fail and show that info
getJsonDecoder : (e -> String) -> Codec e a -> Json.Decode.Decoder a

-- Returns a Result with error information in the Err variant
getJsonDecoder : Codec e a -> Json.Decode.Decoder (Result e a)

-- Matches what you suggested but loses any error information
getJsonDecoder : Codec e a -> Json.Decode.Decoder a
```

**Comment by lue-bird** [comment]
I mean you can get 1 and 3 using 2, so it makes sense only to expose 2.
3:
```elm
getJsonDecoder
    >> Json.Decode.andThen
        (Result.withDefault (Json.Decode.fail "error in codec"))
```
1:
```elm
getJsonDecoder
    >> Json.Decode.andThen
        (Result.extract (Json.Decode.fail << {- toString -}))
```
using [extract from elm-community/result-extra](https://package.elm-lang.org/packages/elm-community/result-extra/latest/Result-Extra#extract).

**Comment by sdeframond** [comment]
I am one-plussing this as it would allow a progressive replacement of Decode/Encode in big code bases.

**Comment by MartinSStewart** [comment]
Yeah sorry, I had forgotten about this issue. I have an implementation that's pretty close to finished already so I'll just sort that out this week.

**Comment by sdeframond** [comment]
Amazing! Thank you'

Mer 05 janv 2022, à 00:40, MartinSStewart a écrit :

**Comment by MartinSStewart** [comment]
elm-serialize version 1.3.0 is now published! `getJsonDecoder: (e -> String) -> Codec e a -> JD.Decoder a` is now added.
