### ISSUE TITLE
very small doc mistake in mapValid

### ISSUE THREAD

**Issue by indique** [MartinSStewart/elm-serialize#5]
There's just a very small documentation mistake I recently found in [mapValid](https://package.elm-lang.org/packages/MartinSStewart/elm-serialize/latest/Serialize#mapValid).

```elm
emailCodec =
    S.string
        |> S.mapValid
            (\text ->
                case Email.fromString {- 'text' should be here -} of
                    Just email ->
                        Ok email

                    Nothing ->
                        Err "Invalid email"
            )
            Email.toString
```

Apart from that, you might want to use [Result.fromMaybe](https://package.elm-lang.org/packages/elm/core/latest/Result#fromMaybe) but that's up to your preference.

```elm
emailCodec =
    S.string
        |> S.mapValid
            (Email.fromString >> Result.fromMaybe "Invalid email")
            Email.toString
```

**Comment by MartinSStewart** [comment]
Thanks, it should be fixed now. I chose to use the more verbose first example, I think it's more clear what it does.
