### ISSUE TITLE
Small doc mistake in byte codec (257 mod 256 is 1, not 2)

### ISSUE THREAD

**Issue by Erudition** [MartinSStewart/elm-serialize#6]
> Warning: values greater than 255 or less than 0 will wrap around. So if you encode -1 you'll get back 255 and if you encode 257 you'll get back 2.

I think this is incorrect, because after 255 comes 256, aka zero. Thus 257 would come out as 1, right?

**Comment by MartinSStewart** [comment]
![image](https://user-images.githubusercontent.com/5068391/110167989-d55cfd00-7df6-11eb-940b-bb696bfcd046.png)
Yup looks like it! I'll fix that now.

**Comment by MartinSStewart** [comment]
Fixed! Thanks for catching the mistake.
